### ISSUE TITLE
Not creating stories in Pivotal

### ISSUE THREAD

**Issue by ericcf** [getsentry/sentry-pivotal#8]
I've installed the plugin, configured the correct API token and project id, but am not seeing new stories get created in Pivotal when I trigger a test exception. The sentry-slack plugin is working for me, so I don't think there's a network/firewall issue. Also, I tested story creation manually from the REPL and it worked.

Something I noticed is that when I tried to configure an Action for a Rule, there's an unhandled JavaScript exception: `TypeError: Cannot read property 'html' of undefined`, and the "Send a notification via" select shows only "Mail" and "Sentry", but not "Pivotal".

Is there some way I can produce a more informative Python stack trace or error log? Thanks!

**Comment by RaviTezu** [comment]
Any update on this? I am facing the same issue and also, I am not able to configure any action for this.

**Comment by RaviTezu** [comment]
Hi ericcf,
 
After enabling the sentry-pivotal plugin, I can see a "Add story" button on the right side of the event page and I am able to create stories using the "Add story" button.  I initially thought, sentry would create stories automatically for every new event on sentry.

Thanks,
RaviTeja

**Comment by ericcf** [comment]
@RaviTezu Thanks! That worked perfectly.
